[package]
name = "spike-sys"
description = "Rust bindings for spike"
exclude = ["riscv-isa-sim"]
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
