name: ckb-mock-tx-types

on:
  pull_request:
    branches: [ main ]
    paths: "ckb-mock-tx-types/**"
  push:
    branches: [ main ]
    paths: "ckb-mock-tx-types/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd ckb-mock-tx-types
        cargo build
