name: ckb-vm-fuzzing-utils

on:
  pull_request:
    branches: [ main ]
    paths: ["ckb-vm-fuzzing-utils/**", "Cargo.toml", "Cargo.lock"]
  push:
    branches: [ main ]
    paths: ["ckb-vm-fuzzing-utils/**", "Cargo.toml", "Cargo.lock"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup
      run: |
        sudo apt install -y protobuf-compiler
    - name: Build
      run: |
        cd ckb-vm-fuzzing-utils
        cargo build
