name: Cargo Publish ckb-x64-simulator

on:
  push:
    tags:
      - 'ckb-x64-simulator-v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cd ckb-x64-simulator && cargo publish
