name: Cargo Publish ckb-vm-fuzzing-utils

on:
  push:
    tags:
      - 'ckb-vm-fuzzing-utils-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup
      run: |
        sudo apt install -y protobuf-compiler
    - name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cd ckb-vm-fuzzing-utils && cargo publish
