name: Cargo Publish ckb-x64-simulator

on:
  push:
    tags:
      - 'ckb-x64-simulator-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup CKB VM
      run: |
        cd ckb-vm-test-suite
        make ckb-vm
    - name: Setup Clang
      run: |
        clang --version
    - name: Setup Rust Target
      run: |
        rustup target add riscv64imac-unknown-none-elf
    - name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cd ckb-x64-simulator && cargo publish
