name: Cargo Publish protobuf-ckb-syscalls

on:
  push:
    tags:
      - 'protobuf-ckb-syscalls-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup
      run: |
        sudo apt install -y protobuf-compiler
    - name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cd protobuf-ckb-syscalls && cargo publish
